### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by JamalLyons** [jiawei397/deno_mongo_schema#1]
Hey, love the project and the support for more mongo drivers in deno. 

Was wondering if you plan to write more docs on the functions/hooks in this lib? The example is good but maybe some commends on what the code is doing would be nice as well.

**Comment by jiawei397** [comment]
Thank you for your use. I'm sorry to be busy these two weeks. I may not have time to do this work. 

This is my inspiration from Mongoose, and inherite from deno_mongo this project.

The method naming is more semantic. For example, the search is `findOne` and `findMany`, the update is `updateOne` and `updateMany`, the search and update is `findOneAndUpdate` and `findByIdAndUpdate`, and the deletion is `deleteMany`, `delete`, `deletebyId` and `findOneAndDelete`. 

The specific parameters should be able to see the type annotation in the IDE, such as this:
```ts
export interface DeleteOptions {
  /**
   * Optional. If true, then when a delete statement fails, return without performing the remaining delete statements.
   * If false, then when a delete statement fails, continue with the remaining delete statements, if any. Defaults to true.
   */
  ordered?: boolean;

  /**
   * Optional. A document expressing the write concern of the delete command. Omit to use the default write concern.
   */
  writeConcern?: Document;

  /**
   * Optional. Specifies the collation to use for the operation.
   * See https://docs.mongodb.com/manual/reference/command/delete/#deletes-array-collation
   */
  collation?: Document;

  /**
   * Optional. A user-provided comment to attach to this command.
   */
  comment?: Document;

  /**
   * The number of matching documents to delete. Specify either a 0 to delete all matching documents or 1 to delete a single document.
   */
  limit?: number;

  /**
   * Optional. A document or string that specifies the index to use to support the query predicate.
   * The option can take an index specification document or the index name string.
   * If you specify an index that does not exist, the operation errors.
   */
  hint?: Document | string;
}
```
I just encapsulated a layer on it.
Although I implemented hooks, I only used it in one place in my work.
Personally, what makes sense is virtual, which reduces a lot of my workload.


Thank you again for your use. I'll start the work in two weeks when I have time. If you have any bugs, please feel free to contact me.

**Comment by ThatGuyJamal** [comment]
Sorry for the late reply, but thanks for the help!
